language: haxe

os:
  - linux

haxe:
  - "4.0.2"
  - development

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib dev three.hx .

script:
  - haxe haxedoc.hxml
  - haxe --cwd examples/basic build.hxml
  - haxe --cwd examples/hello build.hxml
